-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfbJvENHyEbfghsOp
1Ah3CIXPnrsS0TIW5efVNygSkICgCgYIKoZIzj0DAQehRANCAASrD+AKkxLPiatn
iOU3dRFTrixKO5ihOC28bPfXybBKIKuJ9cnRJauiatUYk6ykX3AWL9o4ioud8FA6
bVopoca6
-----END PRIVATE KEY-----